plugins:
  - search
  - awesome-pages
  - mermaid2
site_name: Spinning Up Documentation
theme:
  name: material
  features:
    - navigation.indexes
use_directory_urls: false
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - mdx_math
  - admonition
extra_javascript:
  - resources/mathjax.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - resources/modify.css
