plugins:
  - search
  - awesome-pages
site_name: Spinning Up Documentation
theme:
  name: readthedocs
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.indexes
use_directory_urls: false
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - mdx_math

extra_javascript:
  - resources/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - resources/modify.css
